spring:
  profiles:
    active: ${APP_ENV:dev}
  application:
    name: '@project.artifactId@'
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://admin:dUEIUUtDLCAojL4a@cemprestimo-uf93j.mongodb.net/test?retryWrites=true&w=majority}

java:
  runtime:
    version: 11

server:
  port: ${SERVER_PORT:8081}



security:
  jwt:
    chave-assinatura: YSBsZW1icmUgw6kgYnJhbmNh
    expiracao: 9999999999