spring:
  profiles:
    active: ${APP_ENV:dev}
  application:
    name: '@project.artifactId@'
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://admin:dUEIUUtDLCAojL4a@cemprestimo-uf93j.mongodb.net/test?retryWrites=true&w=majority}

java:
  runtime:
    version: 11

server:
  port: ${SERVER_PORT:8081}

cloudinary:
  api_key: 196455977573897
  api_secret: hvC6b0mb_7jQQbsKgHyD9J9auZE
  cloud_name: defdl1xal

security:
  jwt:
    chave-assinatura: YSBsZW1icmUgw6kgYnJhbmNh
    expiracao: 9999999999