spring:
  profiles:
    active: ${APP_ENV:dev}
  application:
    name: '@project.artifactId@'
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://admin:dUEIUUtDLCAojL4a@cemprestimo-uf93j.mongodb.net/test?retryWrites=true&w=majority}
  thymeleaf:
    encoding: UTF-8
    excluded-view-names: '# comma-separated list of view names   that should be
             excluded from resolution'
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html

  mail:
    default-encoding: UTF-8
    host: smtp.mailgun.org
    username: ${USER_NAME}
    password: ${PASS_WORD} 
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      protocol: smtp
      test-connection: false

java:
  runtime:
    version: 11

server:
  port: ${SERVER_PORT:8081}

cloudinary:
  api_key: 196455977573897
  api_secret: hvC6b0mb_7jQQbsKgHyD9J9auZE
  cloud_name: defdl1xal

security:
  jwt:
    chave-assinatura: YSBsZW1icmUgw6kgYnJhbmNh
    expiracao: 9999999999